version: '3'
services:
  jenkins:
    image: jenkins/jenkins:2.289.3-lts-jdk11
    container_name: jenkins
    network_mode: bridge
    user: root
    ports:
      - "8083:8080"
      - "50003:50000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    volumes_from:
      - jenkins-data
  jenkins-data:
    image: liberstein1/jenkinsdata06082021:1.2
    container_name: jenkins-data
    network_mode: bridge
